<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#60-minute-Blitz" data-toc-modified-id="60-minute-Blitz-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>60 minute Blitz</a></span><ul class="toc-item"><li><span><a href="#Intro-to-PyTorch" data-toc-modified-id="Intro-to-PyTorch-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Intro to PyTorch</a></span><ul class="toc-item"><li><span><a href="#Mutating-Tensors-In-Place" data-toc-modified-id="Mutating-Tensors-In-Place-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Mutating Tensors In-Place</a></span></li><li><span><a href="#Numpy-Type-Indexing" data-toc-modified-id="Numpy-Type-Indexing-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Numpy Type Indexing</a></span></li><li><span><a href="#Converting-Torch-Tensors-to/from-Numpy-Arrays" data-toc-modified-id="Converting-Torch-Tensors-to/from-Numpy-Arrays-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Converting Torch Tensors to/from Numpy Arrays</a></span></li><li><span><a href="#Checking-for-CUDA-Support" data-toc-modified-id="Checking-for-CUDA-Support-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Checking for CUDA Support</a></span></li></ul></li><li><span><a href="#Autograd:-Automatic-Differentiation" data-toc-modified-id="Autograd:-Automatic-Differentiation-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Autograd: Automatic Differentiation</a></span><ul class="toc-item"><li><span><a href="#Variables" data-toc-modified-id="Variables-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Variables</a></span></li><li><span><a href="#Gradients" data-toc-modified-id="Gradients-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Gradients</a></span></li><li><span><a href="#Functions" data-toc-modified-id="Functions-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Functions</a></span></li></ul></li></ul></li></ul></div>

# 60 minute Blitz

Reference: [PyTorch](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

## Intro to PyTorch

In [1]:
from __future__ import print_function
import torch
from torch import *

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  3.6893e+19  0.0000e+00
 3.6893e+19  5.6052e-45  0.0000e+00
 2.4400e+02         nan  6.4853e+02
 4.5841e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  1.2230e-32
[torch.FloatTensor of size 5x3]



In [3]:
x = torch.rand(5, 3)
print(x)


 0.4599  0.5264  0.2863
 0.1912  0.8900  0.7656
 0.1644  0.2435  0.8319
 0.5987  0.6878  0.8781
 0.2899  0.0491  0.4596
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y = torch.rand(5,3)
z = x + y

In [6]:
print(z)


 0.9148  1.3739  0.5925
 0.9693  1.8220  1.2766
 0.6755  0.8606  1.3688
 0.8623  1.5955  1.0600
 1.1270  0.5625  1.1032
[torch.FloatTensor of size 5x3]



In [7]:
print(torch.add(x,y))


 0.1134  0.4897  1.0828
 0.3201  1.1753  1.1135
 1.4612  1.2144  1.1705
 0.6923  1.7053  0.9536
 1.5282  0.9800  0.1514
[torch.FloatTensor of size 5x3]



In [16]:
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)


 1.5237  1.4791  1.1829
 1.2754  1.5603  1.2549
 0.8237  0.7899  0.4985
 0.9333  0.8113  0.4984
 0.3116  0.5223  0.5803
[torch.FloatTensor of size 5x3]



### Mutating Tensors In-Place

Any operation which changes a tensor in-place will be post-fixed with `_`. Eg. `x.add_(y)` is the same as `x = x + y`

In [18]:
y.add(x)


 1.5237  1.4791  1.1829
 1.2754  1.5603  1.2549
 0.8237  0.7899  0.4985
 0.9333  0.8113  0.4984
 0.3116  0.5223  0.5803
[torch.FloatTensor of size 5x3]

In [19]:
y.add_(x)
print(y)


 1.5237  1.4791  1.1829
 1.2754  1.5603  1.2549
 0.8237  0.7899  0.4985
 0.9333  0.8113  0.4984
 0.3116  0.5223  0.5803
[torch.FloatTensor of size 5x3]



### Numpy Type Indexing

All `Tensor` objects support numpy style indexing. Eg. `print(x[:,1])` will print the second column of `x`. `print(x[3,:])` will print the fourth row of `x`.

In [20]:
print(x[:,1])


 0.7789
 0.9438
 0.3392
 0.0058
 0.0243
[torch.FloatTensor of size 5]



In [21]:
print(x[3,:])


 0.4084
 0.0058
 0.1974
[torch.FloatTensor of size 3]



### Converting Torch Tensors to/from Numpy Arrays

We can use the function `Tensor.numpy()` to convert Torch tensors to numpy arrays. However, the resulting array is linked to the original tensor and if we change the tensor then the associated `numpy` array will also reflect that change.

In [22]:
x.numpy()

array([[ 0.68957686,  0.77893943,  0.38970381],
       [ 0.80781305,  0.94381094,  0.82457542],
       [ 0.54702252,  0.33922279,  0.28859544],
       [ 0.40840939,  0.00579275,  0.19744173],
       [ 0.06050696,  0.02430832,  0.58011436]], dtype=float32)

In [23]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [24]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [25]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [26]:
print(b)

[ 2.  2.  2.  2.  2.]


In [28]:
import numpy as np

In [29]:
a = np.ones(5)

In [30]:
b = torch.from_numpy(a)
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [31]:
np.add(a,1,out = a)

array([ 2.,  2.,  2.,  2.,  2.])

In [32]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

### Checking for CUDA Support

In [8]:
torch.cuda.is_available()

False

## Autograd: Automatic Differentiation

### Variables

In [33]:
from torch.autograd import Variable

In [34]:
x = Variable(torch.ones(2,2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [35]:
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [36]:
print(x.grad_fn)

None


In [37]:
print(y.grad_fn)

In [38]:
x.sin()

Variable containing:
 0.8415  0.8415
 0.8415  0.8415
[torch.FloatTensor of size 2x2]

In [39]:
x.mean()

Variable containing:
 1
[torch.FloatTensor of size 1]

In [41]:
z = y * y * 3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



### Gradients

The variable `out` is defined as the mean of all the elements of the tensor `z`:
$$ \text{out} = \frac{1}{4}\sum_{i,j} z_{ij} $$
`z` is related to `x` via `z = y * y * 3 = (x + 2)^2 * 3`, or:
$$ z_{ij} = 3 (x_{ij} + 2)^2 $$
Since $x_{ij} = 1$, we have $ z_{ij} = 27 $ and for the derivative:
$$ \frac{d}{d x_{kl}} z_{ij} = 6 (x_{kl} + 2) \delta^k_i \delta^l_j $$
where $\delta^k_i$ is the Kronecker delta:
\begin{equation}
    \delta^k_l = \begin{cases}
                    0 \text{ if } k \ne l \\
                    1 \text{ if } k = l
                 \end{cases}
\end{equation}
For the gradient of $\text{out}$ w.r.t `x`, we find:
\begin{align}
    \frac{d}{d x_{kl}} \text{out} & = \frac{1}{4} \sum_{ij} \frac{d}{d x_{kl}} z_{ij} \\
                                  & = \frac{1}{4} \sum_{ij} 6 (x_{kl} + 2) \delta^k_i \delta^l_j \\
                                  & = \frac{3}{2} (x_{kl} + 2) = 9/2 = 4.5
\end{align}

In [42]:
out.backward()

In [47]:
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [48]:
x = torch.randn(3)
x


 0.6367
 0.8964
 0.0704
[torch.FloatTensor of size 3]

In [49]:
x = Variable(torch.randn(3), requires_grad=True)

In [51]:
y = x * 2
print(y)

Variable containing:
 1.5553
 3.3402
-3.8452
[torch.FloatTensor of size 3]



In [53]:
while y.data.norm() < 1000:
    y = y * 2
print(y)

Variable containing:
 398.1570
 855.0854
-984.3682
[torch.FloatTensor of size 3]



In [63]:
y.view(3)

Variable containing:
 398.1570
 855.0854
-984.3682
[torch.FloatTensor of size 3]

In [66]:
y.grad_fn

### Functions

In [67]:
from torch.autograd import Function

In [70]:
Function(y)