<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Reference:-Baby-Steps" data-toc-modified-id="Reference:-Baby-Steps-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Reference: <a href="http://deeplearning.net/software/theano/tutorial/adding.html" target="_blank">Baby Steps</a></a></span><ul class="toc-item"><li><span><a href="#Logistic-Function" data-toc-modified-id="Logistic-Function-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Logistic Function</a></span></li><li><span><a href="#Functions-with-multiple-outputs" data-toc-modified-id="Functions-with-multiple-outputs-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Functions with multiple outputs</a></span></li><li><span><a href="#Setting-Default-Values-for-Arguments" data-toc-modified-id="Setting-Default-Values-for-Arguments-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Setting Default Values for Arguments</a></span></li><li><span><a href="#Shared-Variables" data-toc-modified-id="Shared-Variables-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Shared Variables</a></span><ul class="toc-item"><li><span><a href="#Sharing-Variables-in-Multiple-Functions" data-toc-modified-id="Sharing-Variables-in-Multiple-Functions-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Sharing Variables in Multiple Functions</a></span></li><li><span><a href="#Reset-Shared-Variable" data-toc-modified-id="Reset-Shared-Variable-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Reset Shared Variable</a></span></li></ul></li></ul></li></ul></div>

# Reference: [Baby Steps](http://deeplearning.net/software/theano/tutorial/adding.html)

In [1]:
import theano
import theano.tensor as T

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [2]:
import numpy as np

In [3]:
a = T.vector()
b = T.vector()
out = a**2 + b**2 + 2*a*b

In [6]:
f = theano.function([a,b], out)

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x}(TensorConstant{2.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/tensor/opt.py", line 6516, in constant_folding
    no_recycling=[], impl=impl)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x}(TensorConstant{2.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/opt.py", line 2034, in process_node
    replacements = lopt.transform(node)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/tensor/opt.py", line 6516, in constant_folding
    no_recycling=[], impl=impl)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/Users/deepak/miniconda3/lib/python3.6/site-packages/theano/gof

KeyboardInterrupt: 

In [5]:
print(f([1,1,1],[-1,-1,-1]))

NameError: name 'f' is not defined

In [8]:
x = np.random.rand(3)
y = np.random.rand(3)

In [9]:
x,y

(array([ 0.50010861,  0.21448927,  0.68804353]),
 array([ 0.1864099 ,  0.67972265,  0.38544939]))

In [10]:
f(x,y)

array([ 0.47130767,  0.79961496,  1.15238706])

## Logistic Function

Reference: [Examples](http://deeplearning.net/software/theano/tutorial/examples.html)
$$ s(x) = \frac{1}{1 + e^{-x}} $$


In [11]:
x = T.dmatrix()

In [12]:
s = 1/(1+T.exp(-x))

In [13]:
logistic = theano.function([x],s)

In [14]:
x = np.random.rand(2,2)

In [15]:
x

array([[ 0.34737163,  0.66959193],
       [ 0.96782668,  0.90765783]])

In [16]:
logistic(x)

array([[ 0.58598006,  0.66141178],
       [ 0.7246861 ,  0.71252064]])

In [29]:
np.identity(2)+np.exp(-x)

array([[ 1.70654271,  0.51191744],
       [ 0.3799078 ,  1.40346811]])

In [36]:
np.linalg.inv(np.identity(2)+np.exp(-x))

array([[ 0.63776703, -0.23262663],
       [-0.17263853,  0.77549085]])

In [35]:
np.linalg.inv?

## Functions with multiple outputs

In [38]:
a, b = T.dmatrices(2)

In [43]:
diff = a - b

In [44]:
abs_diff = abs(diff)
diff_squared = diff**2

In [45]:
f = theano.function([a,b],[diff,abs_diff,diff_squared])

In [48]:
a = np.random.rand(2,3)
b = np.random.rand(2,3)

In [51]:
%pprint

Pretty printing has been turned ON


In [53]:
f(a,b)

[array([[-0.06648919,  0.18854489, -0.82149001],
        [-0.64806831,  0.34986794,  0.5175316 ]]),
 array([[ 0.06648919,  0.18854489,  0.82149001],
        [ 0.64806831,  0.34986794,  0.5175316 ]]),
 array([[ 0.00442081,  0.03554918,  0.67484583],
        [ 0.41999253,  0.12240757,  0.26783896]])]

In [57]:
a = np.random.rand(1,1)
b = np.random.rand(1,1)
f(a,b)

[array([[ 0.15126622]]), array([[ 0.15126622]]), array([[ 0.02288147]])]

## Setting Default Values for Arguments

In [58]:
from theano import In
from theano import function

In [59]:
x, y = T.dscalars(2)
z = x + y

In [61]:
f = function([x,In(y,value=1)],z)

In [62]:
f(10)

array(11.0)

## Shared Variables

In [63]:
from theano import shared

In [84]:
state = shared(0)

In [90]:
inc = T.iscalar('inc')

In [91]:
accumulator = function([inc],state,updates=[(state,state+inc)])

In [92]:
accumulator(20)

array(0)

In [94]:
accumulator(21)

array(20)

In [95]:
state.get_value()

array(41)

**Note**: If in the above code, we do not provide a name for the variable `inc` at time of variable definition:

```
inc = T.iscalar()
```
then the value of the shared variable `state` will **not** be updated on successive calls of the `accumulator` function.

### Sharing Variables in Multiple Functions

In [96]:
decrement = function([inc],state,updates=[(state,state-inc)])

In [97]:
state.get_value()

array(41)

In [98]:
decrement(39)

array(41)

In [99]:
state.get_value()

array(2)

### Reset Shared Variable

In [101]:
state.set_value(0)
state.get_value()

array(0)

In [102]:
np.random.randn?

In [103]:
np.random.randn(10,2)

array([[ 0.08362404, -0.03264939],
       [ 0.28277901,  0.41418193],
       [ 1.27939555,  0.0553451 ],
       [ 0.94212585, -0.5400929 ],
       [-0.37445055, -2.56215311],
       [ 1.34317618,  0.59439305],
       [ 0.78302303, -0.54709079],
       [-0.54863752,  1.0544807 ],
       [ 0.1539726 , -0.21620428],
       [-0.64147888,  0.37727372]])

In [107]:
np.random.randint(size=10,low=0,high=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])